---
title: "Short Term Trends for SOE inclusion"
output: html_document
---

```{r, warning=FALSE, message=FALSE, echo=FALSE}
#library(tidyverse)
#library(ecodata)
```

```{r,warning=FALSE, message=FALSE, echo=FALSE,  code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/human_dimensions_NE.Rmd-setup.R")}
```

```{r, warning=FALSE, message=FALSE, echo=FALSE, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/human_dimensions_NE.Rmd-GIS-setup.R")}
```


### Examples: geom_lm() 

#### Human Dimensions

```{r, warning=FALSE, message=FALSE, echo=FALSE}
ecodata::ppr %>% 
  dplyr::filter(Var == "Ryther") %>% 
  dplyr::group_by(EPU) %>% 
  dplyr::mutate(hline = mean(Value), 
                gr_up = c(1.1),
                rd_up = c(5),
                gr_lw = c(0.3),
                rd_lw = c(3)) %>% 
  dplyr::filter(EPU != "MAB") %>% 
  ggplot2::ggplot() +
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf) +
  ggplot2::geom_ribbon( aes(ymin = gr_lw, ymax = gr_up, x = Time), fill = "darkolivegreen3", alpha = 0.5)+
  ggplot2::geom_ribbon( aes(ymin = rd_lw, ymax = rd_up, x = Time), fill = "sandybrown", aplha = 0.5)+
  arfit::geom_lm(aes(x = Time, y = Value))+
  ggplot2::geom_point(aes(x = Time, y = Value))+
  ggplot2::geom_line(aes(x = Time, y = Value))+
  ggplot2::scale_x_continuous(expand = c(0.05, 0.05)) +
  ggplot2::facet_wrap( ~ EPU)+
  ggplot2::ggtitle("Ryther Index")+
  ggplot2::ylab("mt km-2 y-1")+
  ggplot2::xlab(element_blank())+
  ecodata::theme_ts()+
  ecodata::theme_title()+
  ecodata::theme_facet()
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
landings_rec <- ecodata::recdat %>% 
  dplyr::filter(EPU == "NE",
         Var == "Recreational Seafood") %>% 
  dplyr::mutate(hline = mean(Value))

series.col <- "black"

rec_landings <- ggplot2::ggplot(data = landings_rec)+
  
  #Highlight last ten years
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf) +
  ecodata::geom_gls(aes(x = Time, y = Value,
               group = Var),
             alpha = trend.alpha, size = trend.size) +
  arfit::geom_lm(aes(x = Time, y = Value))+
  ggplot2::geom_line(aes(x = Time, y = Value, color = Var), size = lwd) +
  ggplot2::geom_point(aes(x = Time, y = Value, color = Var), size = pcex) +
  ggplot2::ggtitle("NE Recreational seafood harvest")+
  ggplot2::scale_y_continuous(labels = function(l){trans = l / 1000000})+
  ggplot2::scale_x_continuous(breaks = seq(1985, 2020, by = 5), expand = c(0.01, 0.01)) +
  ggplot2::scale_color_manual(values = series.col, aesthetics = "color")+
  ggplot2::guides(color = FALSE) +
  # Plotly can not use "expression" so follow notes below
  ggplot2::ylab(expression("Landings (10"^6*" lbs)")) + # Use this for HTML version
  
  ggplot2::xlab(element_blank())+
  #ggplot2::ylab(expression("Fish caught (10"^6"*n)")) + #Use this for SOEs and anything pdf 
  ggplot2::geom_hline(aes(yintercept = hline, color = Var),
           size = hline.size,
           alpha = hline.alpha,
           linetype = hline.lty) +
  ecodata::theme_ts()+
  ecodata::theme_title()

#plotly::ggplotly(rec_landings) # plotly removes geom_gls
rec_landings

```

### Megafauna

```{r}
ecodata::narw %>% 
  dplyr::filter(Var != "Calves") %>% 
  tidyr::spread(Var, Value) %>% 
  dplyr::rename(Value = Median) %>% 
  dplyr::mutate(Value = as.numeric(Value), 
                Time = as.numeric(Time),
                Lower95 = as.numeric(Lower95), 
                Upper95 = as.numeric(Upper95),
                hline = mean(Value, na.rm = T)) %>% 
  ggplot2::ggplot() +
#Highlight last ten years
  ggplot2::annotate("rect", fill = shade.fill, alpha = shade.alpha,
      xmin = x.shade.min , xmax = x.shade.max,
      ymin = -Inf, ymax = Inf) +
  ggplot2::geom_line(aes(x = Time, y = Value), size = lwd-0.75) +
  ggplot2::geom_point(aes(x = Time, y = Value), size = pcex-0.75) +
  arfit::geom_lm(aes(Time, y = Value))+
  ggplot2::geom_ribbon(aes(ymin = Lower95, ymax = Upper95, x = Time), alpha = 0.3)+
  ggplot2::scale_x_continuous(expand = c(0.01, 0.01)) +
  ggplot2::guides(color = FALSE) +
  ggplot2::ggtitle("NARW abundance") +
  ggplot2::ylab(expression("Abundance (n)")) +
  ggplot2::xlab(element_blank())+
  ggplot2::geom_hline(aes(yintercept = hline),
          color = "black",
          size = hline.size,
          alpha = hline.alpha,
          linetype = hline.lty) +
  ecodata::theme_ts()+
  ecodata::theme_title()
```

#### Low Trophic

```{r}
out_chl <- ecodata::chl_pp %>% 
  dplyr::filter(EPU == "MAB",
         stringr::str_detect(Var, "MONTHLY_CHLOR_A_MEDIAN")) %>% 
  tidyr::separate(.,Time, into = c("Cat", "Time2"), sep = "_") %>% 
  tidyr::separate(.,Time2, into = c("Year", "Month"), sep = 4)%>% 
    dplyr::mutate(Month = plyr::mapvalues(Month, from = c("01","02","03","04","05","06",
                                                   "07","08","09","10","11","12"),
                                   to = c(month.abb)))%>% 
  dplyr::filter(!Value == "NA") %>% 
  dplyr::group_by(Month) %>% 
  dplyr::mutate(hline = mean(Value), 
                Year = as.numeric(Year))

out_chl$Month <- factor(out_chl$Month, levels = month.abb)


chl_cci <- ggplot2::ggplot(out_chl) +
   # geom_gls(aes(x = Year, y = Value, group = Month))+
    ggplot2::geom_point(aes(x = Year, y = Value, group = Month)) +
    ggplot2::geom_line(aes(x = Year, y = Value, group = Month)) +
    # ggplot2::scale_x_discrete(name = "", breaks = seq(min(out_chl$Year),max(out_chl$Year),10)) +
    #        geom_hline(aes(yintercept = hline),
    #       size = hline.size,
    #       alpha = hline.alpha,
     #     linetype = hline.lty) +
    ggplot2::facet_wrap(Month~., ncol = 12) +
    arfit::geom_lm(aes(x = Year, y = Value)) +
    ggplot2::ggtitle("Monthly median CHL") +
    ggplot2::ylab(expression("CHL (mg m"^-3*")")) +
    ecodata::theme_facet() +
    ggplot2::theme(axis.text.x = element_text(angle=45, hjust = 1),
          panel.spacing = unit(.5, "lines"),
          plot.margin = unit(c(0.1, 0, 0, 0), "cm"))+
  ecodata::theme_title()

chl_cci
```


```{r}
out_pp <- ecodata::chl_pp %>% 
  dplyr::filter(EPU == "MAB",
         stringr::str_detect(Var, "MONTHLY_PPD_MEDIAN")) %>% 
  tidyr::separate(.,Time, into = c("Cat", "Time2"), sep = "_") %>% 
  tidyr::separate(.,Time2, into = c("Year", "Month"), sep = 4) %>% 
  dplyr::mutate(Month = plyr::mapvalues(Month, from = c("01","02","03","04","05","06",
                                                   "07","08","09","10","11","12"),
                                   to = c(month.abb))) %>% 
  dplyr::filter(!Value == "NA") %>% 
  dplyr::group_by(Month) %>% 
  dplyr::mutate(hline = mean(Value), 
                Year = as.numeric(Year))

out_pp$Month <- factor(out_pp$Month, levels = month.abb)


pp_cci <- ggplot2::ggplot(out_pp) +
   # geom_gls(aes(x = Year, y = Value, group = Month))+
    ggplot2::geom_point(aes(x = Year, y = Value, group = Month)) +
    ggplot2::geom_line(aes(x = Year, y = Value, group = Month)) +
  arfit::geom_lm(aes(x = Year, y = Value))+
    #ggplot2::scale_x_discrete(name = "", breaks = seq(min(out_pp$Year),max(out_pp$Year),10)) +  
    # ggplot2::geom_hline(aes(yintercept = hline),
    #        size = hline.size,
    #        alpha = hline.alpha,
    #        linetype = hline.lty) +
    ggplot2::facet_wrap(Month~., ncol = 12) +
    ggplot2::ggtitle("Monthly median PPD") +
    ggplot2::ylab(expression("PP (gC m"^-2*" d"^-1*")")) +
    ecodata::theme_facet() +
    ggplot2::ylab("Time")+
    ggplot2::theme(axis.text.x = element_text(angle=45, hjust = 1),
          panel.spacing = unit(0.5, "lines"),
          plot.margin = unit(c(0.1, 0, 0, 0), "cm"))+
  ecodata::theme_title()

pp_cci
```



